sonar.projectKey=gitops-sample-app
sonar.projectName=gitops-sample-app
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.exclusions=dist/**,node_modules/**
sonar.sourceEncoding=UTF-8
